import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MenuProvider } from "./context/MenuContext";
import { ViewTransitions } from "next-view-transitions";
import { ThemeProvider } from "./components/ThemeProvider";
import SmoothScrollingWrapper from "@/utils/SmoothScrollingWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ViewTransitions>
            {/* <SmoothScrollingWrapper> */}
              <MenuProvider>{children}</MenuProvider>
            {/* </SmoothScrollingWrapper> */}
          </ViewTransitions>
        </ThemeProvider>
      </body>
    </html>
  );
}
