import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ViewTransitions } from "next-view-transitions";
import { ThemeProvider } from "./components/ThemeProvider";
import SmoothScrollingWrapper from "@/utils/SmoothScrollingWrapper";
import { getCurrentUser } from "../src/lib/getCurrentUser";
import { UserProvider } from "./context/UserContext";
import ApolloProviders from "./providers/ApolloProviders";
import { SidebarConfigProvider } from "./context/sidebar-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
          <link
          rel="preload"
          href="/fonts/FKScreamerTrial-Bold-BF6571330a76e9b.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
      </head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarConfigProvider>
            <ViewTransitions>
              {/* <SmoothScrollingWrapper> */}

              <ApolloProviders>{children}</ApolloProviders>

              {/* </SmoothScrollingWrapper> */}
            </ViewTransitions>
          </SidebarConfigProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
