import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MenuProvider } from "./context/MenuContext";
import { ViewTransitions } from "next-view-transitions";
import { ThemeProvider } from "./components/ThemeProvider";
import SmoothScrollingWrapper from "@/utils/SmoothScrollingWrapper";
import { getCurrentUser } from "../src/lib/getCurrentUser";
import { UserProvider } from "./context/UserContext";
import ApolloProviders from "./providers/ApolloProviders";
import { SidebarConfigProvider } from "./context/sidebar-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  console.log("Current User in Layout:", user);
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            <SidebarConfigProvider>
              <ViewTransitions>
            {/* <SmoothScrollingWrapper> */}
            <MenuProvider>
              <ApolloProviders>
                <UserProvider user={user}>{children}</UserProvider>
              </ApolloProviders>
            </MenuProvider>
            {/* </SmoothScrollingWrapper> */}
          </ViewTransitions>
            </SidebarConfigProvider>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
