import type { Metadata } from "next";
import Script from "next/script";

import "./styles/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <Script id="open-dat-gui-flag" strategy="beforeInteractive">
        {`window.OPEN_DAT_GUI = true;`}
      </Script> */}
      {children}
    </>
  );
}
